timezone_map = {
    # 繁體中文
    "台灣": "Asia/Taipei",
    "日本": "Asia/Tokyo",
    "韓國": "Asia/Seoul",
    "中國": "Asia/Shanghai",
    "香港": "Asia/Hong_Kong",
    "新加坡": "Asia/Singapore",
    "泰國": "Asia/Bangkok",
    "越南": "Asia/Ho_Chi_Minh",
    "印度": "Asia/Kolkata",
    "美國東岸": "America/New_York",
    "美國西岸": "America/Los_Angeles",
    "芝加哥": "America/Chicago",
    "丹佛": "America/Denver",
    "英國": "Europe/London",
    "法國": "Europe/Paris",
    "德國": "Europe/Berlin",
    "義大利": "Europe/Rome",
    "西班牙": "Europe/Madrid",
    "澳洲東岸": "Australia/Sydney",
    "澳洲西岸": "Australia/Perth",
    "紐西蘭": "Pacific/Auckland",
    
    # English names
    "Taiwan": "Asia/Taipei",
    "Taipei": "Asia/Taipei",
    "Japan": "Asia/Tokyo",
    "Tokyo": "Asia/Tokyo",
    "Korea": "Asia/Seoul",
    "Seoul": "Asia/Seoul",
    "China": "Asia/Shanghai",
    "Shanghai": "Asia/Shanghai",
    "Beijing": "Asia/Shanghai",
    "Hong Kong": "Asia/Hong_Kong",
    "Singapore": "Asia/Singapore",
    "Thailand": "Asia/Bangkok",
    "Bangkok": "Asia/Bangkok",
    "Vietnam": "Asia/Ho_Chi_Minh",
    "India": "Asia/Kolkata",
    "New York": "America/New_York",
    "Los Angeles": "America/Los_Angeles",
    "Chicago": "America/Chicago",
    "Denver": "America/Denver",
    "UK": "Europe/London",
    "London": "Europe/London",
    "France": "Europe/Paris",
    "Paris": "Europe/Paris",
    "Germany": "Europe/Berlin",
    "Berlin": "Europe/Berlin",
    "Italy": "Europe/Rome",
    "Rome": "Europe/Rome",
    "Spain": "Europe/Madrid",
    "Madrid": "Europe/Madrid",
    "Sydney": "Australia/Sydney",
    "Melbourne": "Australia/Melbourne",
    "Perth": "Australia/Perth",
    "Auckland": "Pacific/Auckland"
}